# Generated by Django 2.2 on 2019-04-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaModel',
            fields=[
                ('pessoa_id', models.AutoField(primary_key=True, serialize=False)),
                ('pessoa_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('pessoa_logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('pessoa_numero', models.CharField(max_length=5, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['pessoa_nome'],
            },
        ),
    ]
